### ISSUE TITLE
Plugin is not activated automatically 

### ISSUE THREAD

**Issue by 42sol-eu** [susisu/markdown-table-editor#1]
what do I have to do to activate the plugin.
Esc seems to stop the table mode. But how to enter it?

**Comment by susisu** [comment]
It indeed becomes active automatically if the cursor is in table (i.e. in a line starts with a vertical bar `|`).

If you type like below, for example (the cursor position is shown by `_`)

```
| ABC_
```

then just pressing `tab` (next-cell) produces

```
| ABC | _
| --- |
```

Other operations can be done in the same way.

**Comment by 42sol-eu** [comment]
OK, that sounds sensible. But it does not hapen in my atom (running on windows - which should not be a problem). The version of atom is 1.15.0 (lastest one) 64bits.

I tested disabling all other plugins that might interfere, without success.
Are there any plugins that might support the behavior on your configuration?

**Comment by susisu** [comment]
I guess you don't set editor's grammar to Markdown, or don't have the grammar in the active grammars list.
If you use [language-markdown](https://atom.io/packages/language-markdown) package, add `text.md` to "Grammars" in the markdown-table-editor settings, and then try it again.

**Comment by susisu** [comment]
I have a (probably) same problem reported and it was solved.
Based on that, I created a list for solving the problem, so please follow it.
If you still have some problem about the package, I'm sorry but please notify me.

0. Let the cursor be in a table
1. Open the command palette (`ctrl-shift-p` or `cmd-shift-p`) and search for "Next Cell" command
    - Not found: Go to 2
    - Found: Go to 3
2. Make sure that the grammar is set to "Markdown" and it is listed in "Grammars" (like `source.gfm, text.md`)
    - Not solved: Go to 3
3. Make sure that "Keybindings" is enabled and the package is not listed in "Packages With Keymaps Disabled" of Core settings
    - Not solved: Go to 4
4. Open the keybindings resolver (`ctrl-.` or `cmd-.`), push `tab`, and find "markdown-table-editor:next-cell"
    - Found but disabled: Go to 5
    - Not found: I have no idea...  
5. Disable the conflicting package or override keymaps

Thanks.

**Comment by cdpb** [comment]
hab the same error, fixed it with changing the view from `Auto Detect` /  `Plain Text` to `GitHub Markdown`
