### ISSUE TITLE
表格对齐问题

### ISSUE THREAD

**Issue by anson2416** [susisu/markdown-table-editor#10]
在Demo里面，Name Color的表头会根据表格的内容而对齐，请问是怎样做到的？
在自己的电脑上使用MTE的时候，表头跟表格的内容是不对齐的。（注意）显示效果没有问题，很好。

| Name | Color | Mass [g] |
| --- | --- | --- |
| Alex | Red | 100 |
| Dell | Blue | 200 |

**Comment by susisu** [comment]
对不起，我不明白中文。
Sorry, I don't understand Chinese.

You mean that the alignment of the header row is inconsistent with the demo, and you want to align like the demo, right?
It can be configured from the package settings.
<img width="348" alt="2017-10-01 12 04 47" src="https://user-images.githubusercontent.com/2443491/31051345-fb04dde2-a6a0-11e7-9e1d-eb92289c951f.png">

By default (`Follow column's alignment`), the header is aligned as the other cells in the column are.
```
| Name   | Color  | Mass [g] |
| ------ | ------ | -------- |
| apple  | red    | 180      |
| banana | yellow | 120      |
| grape  | green  | 150      |
```
In the demo, it uses `Center` and the header is always aligned center.
(Actually this is the old default and I haven't updated the demo yet.)
```
|  Name  | Color  | Mass [g] |
| ------ | ------ | -------- |
| apple  | red    | 180      |
| banana | yellow | 120      |
| grape  | green  | 150      |
```

**Comment by anson2416** [comment]
Hi Susisu, sorry that i used Chinese in the original issue. In the demo (GIF), the cell length will be auto increated. 

I try to type:
| Name | color | Mass [g] |

But the output is not formatted as the demo (align the same size).
| --- | --- | --- |
* there are 3 - generated.

Can you share how to do as the demo shows?

**Comment by susisu** [comment]
@anson2416  Thank you for explaining in English!

Perhaps your "Format Type" setting is set to "Each Row", isn't it?
If so, set it to "Whole Table" and it will work as the demo.
![screen shot 2017-10-10 at 16 47 32](https://user-images.githubusercontent.com/2443491/31374914-cd1cfea0-adda-11e7-8d63-2e7706d669ba.png)

**Comment by anson2416** [comment]
@susisu Amazing! I can do it with your instrution. Thanks a lot for your time and thanks a lot for your plug-in which make my MD editing easier!

```
| Name | Color | Mass [g] |
| ---- | ----- | -------- |
|      |       |          |
```
