### ISSUE TITLE
Bad Format for Chinese Characters

### ISSUE THREAD

**Issue by zhouxi4oling** [susisu/markdown-table-editor#11]
<img width="674" alt="2017-10-12 10 16 58" src="https://user-images.githubusercontent.com/10398547/31500822-1f408a7c-af2e-11e7-936f-3af1dc615c9b.png">

**Comment by susisu** [comment]
You should use a monospaced font that is compatible with Chinese characters.
See #5 and #9.

**Comment by zhouxi4oling** [comment]
Thank you for you help :)
