### ISSUE TITLE
when typing chinese character. it wouldn`t align.

### ISSUE THREAD

**Issue by zk4** [susisu/markdown-table-editor#5]
![image](https://user-images.githubusercontent.com/996674/28681615-b2194f48-732c-11e7-9c60-5814bc799155.png)

Chinese character`s width is twice than ascii.  hope this helps.

**Comment by zk4** [comment]
the text :
|   我们在一起   |      一志的世界      |
| -------------- | -------------------- |
| 如果一起起的话 | 也没有什么可以发生的 |

**Comment by susisu** [comment]
In your picture, the Chinese characters' widths are actually not twice, right?
You should use a monospace font compatible with Chinese characters, such as [Noto Sans Mono CJK](https://github.com/googlei18n/noto-cjk), and it will align!

**Comment by zk4** [comment]
you save my day! thanks!
