### ISSUE TITLE
how can I handle the big cell

### ISSUE THREAD

**Issue by airclear** [susisu/markdown-table-editor#7]
when I input a big cell , it will format like this:

![image](https://user-images.githubusercontent.com/4103690/30260545-9f06765a-96fa-11e7-935a-28c5ff715eaf.png)

It looks very confusing, What can I do?

**Comment by susisu** [comment]
Switching format type to "Each Row" may help; a single big cell will not affect other cells.

<img width="732" alt="2017-09-12 1 34 02" src="https://user-images.githubusercontent.com/2443491/30285864-8824904c-975a-11e7-84dc-dc253fbd9ec3.png">

It can also be switched from the command palette by selecting "Markdown Table Editor: Switch Format Type" ;)
