### ISSUE TITLE
Some 2-byte characters unpleasantly shift a position of the column border.

### ISSUE THREAD

**Issue by moriyas1984** [susisu/markdown-table-editor#8]
I'm often using the nice package to write documents, thanks.

But I found some cell borders formatted by the package  when the previous cell includes some kinds of 2-byte characters as follows.

![image](https://user-images.githubusercontent.com/18719417/30733914-fadad45a-9fb3-11e7-8925-6435bce7bfaf.png)

In above, `→(2-byte arrow) ` and `※(2-byte asterisk)` affect to positions of the next column borders. But other 2-byte characters (`あ`, `い`, and so on) don't affect.
I'll appreciate if you fix the unpleasant behavior.

For the reference, I’m using the following packages related to markdown writing.

https://github.com/ewnd9/hyperclick-markdown
https://atom.io/packages/markdown-document
https://atom.io/packages/markdown-preview-enhanced
https://atom.io/packages/markdown-scroll-sync
https://atom.io/packages/markdown-table-editor
https://atom.io/packages/markdown-themeable-pdf
https://atom.io/packages/markdown-writer

Thanks.

**Comment by susisu** [comment]
Turning on "Treat East Asian Ambiguous Characters As Wide" from the settings will fix it. 😃 
Some characters like `→` and `※` have "Ambiguous" width (see: http://www.unicode.org/reports/tr11/) and they are treated as narrow (half-width) by default.

You can also override this behavior by adding characters to "Always Wide/Narrow Characters".

**Comment by moriyas1984** [comment]
I've enabled the checkbox and it's working well, thanks!
