### ISSUE TITLE
How can I beautify the Chinese.

### ISSUE THREAD

**Issue by youngjuning** [susisu/markdown-table-editor#9]

**Comment by susisu** [comment]
What do you mean?
I can't help you without any information.

* To align table cells correctly, you must use a monospace font (like [Noto-Sans-Mono-CJK](https://github.com/googlei18n/noto-cjk)).
* Turning on "Treat East Asian Ambiguous Characters As Wide" is recommended for Chinese environment.

**Comment by youngjuning** [comment]
I  use Source Code Pro.Is That's a  monospace font?

**Comment by youngjuning** [comment]
I just mean I can not align table cells correctly when some Chinese character in. I use Source Code Pro font.

**Comment by susisu** [comment]
Yes, Source Code Pro is a monospaced font, but it does not include Chinese glyphs (if I remember correctly) and some alternative (non-monospaced) font will be used for those characters.

**Comment by youngjuning** [comment]
@susisu Best wish with you. That’s useful to me. I will be fun in following you.
